# HTTP Config
server:
  port: 8000
  
# Spring Config
spring:
  application:
    name: currency-exchange-service
  cloud:
    config:
      enabled: false
    discovery:
      enabled: true
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
  profiles:
    active:
    - qa

# Spring Cloud Config
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    fetch-registry: true
    
ribbon:
  eureka:
    enabled: true